FROM mcr.microsoft.com/playwright/python:v1.50.0-jammy

WORKDIR /app

COPY requirements.txt ./
COPY requirements-worker.txt ./
RUN pip install --no-cache-dir -r requirements-worker.txt

COPY . .

CMD ["python", "-m", "test_runner.worker"]
